### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by moh1122** [rubygarage/shopapp-ios#162]
Hello
Great app im working on this but I want to ask about the payment gateways. Can I only add apple pay or I should have another payment gateway to use?

**Comment by plzen** [comment]
Hello @moh1122,

You can use your default gateway for processing payments with credit cards  https://help.shopify.com/manual/payments. 

Apple Pay it's additional feature.

**Comment by moh1122** [comment]
Hello
thank for your reply honestly I dont have a payment gateway yet can I add apple in app purchase instead?

**Comment by plzen** [comment]
We've just tested processing Apple Pay payments without payment gateway - Shopify returns error that payment gateway is not configured. So, you can't use Apple Pay without payment gateway.

You can choose any gateway which support Apple Pay - https://developer.apple.com/apple-pay/#payment-providers
