### ISSUE TITLE
ShopifyAPI Error

### ISSUE THREAD

**Issue by TALAL16** [rubygarage/shopapp-ios#191]
**Hello**
**I get error when I add** " container.register(API.self) { _ in
            return ShopifyAPI(apiKey: "API KEY",
                              shopDomain: "SHOP DOMAIN",
                              adminApiKey: "ADMIN API KEY",
                              adminPassword: "ADMIN PASSWORD",
                              applePayMerchantId: "APPLE PAY MERCHANT ID")
            }
            .inObjectScope(.container) "

**in DataAssembly , the error is "  Use of unresolved identifier 'ShopifyAPI' "**

**Comment by plzen** [comment]
Hello @TALAL16,

To get access for ShopifyAPI, you need `import ShopApp_Shopify` at the top of `DataAssembly.swift` file.

**Comment by TALAL16** [comment]
Thank you 👍🏻

**Comment by mediakliq** [comment]
Hello the app loads and finds my collection names but it's not finding products or Default on home. I'm getting errors:

- Could not find default
- There are no products yet (in collections that do have products)

Thanks

**Comment by radyslavkrechet** [comment]
@mediakliq, hi!

As I understand, you don't see any product on the home screen of the app in "Last Arrivals" and "Popular" sections. Make sure that your products are available in "Online Store" and "Mobile shop". You can check it on the details screen of each product in Shopify admin panel, just look at the "Product availability" block on this page.

Let me know if it's not the reason for your problem and if so, you can provide more information and I'll try to help you.
