### ISSUE TITLE
Getting a few issues when trying to build

### ISSUE THREAD

**Issue by marcowenk** [rubygarage/shopapp-ios#193]
<img width="442" alt="Bildschirmfoto 2019-04-19 um 03 08 52" src="https://user-images.githubusercontent.com/8598325/56399785-79b01780-6250-11e9-8298-274fc2046f6a.png">

**Comment by marcowenk** [comment]
can someone help with that? would be nice

**Comment by radyslavkrechet** [comment]
I can't reproduce it. Could you clarify information on this issue: Xcode version, CoreStore version and Swift version of this pod. You also can try to fund some information in CoreStore's Github repo.

**Comment by marcowenk** [comment]
Hi, thanks for the quick answer.
I'm using everything like you described, could fix most problems, but I still get this one (I removed the keys only for the screenshot):

<img width="1118" alt="Bildschirmfoto 2019-04-23 um 05 01 26" src="https://user-images.githubusercontent.com/8598325/56550107-03c7eb00-6585-11e9-9b17-58318b14f961.png">

**Comment by radyslavkrechet** [comment]
@marcowenk, make sure that you have the next imported modules in this file:
```
import Swinject
import ShopApp_Gateway
import ShopApp_Shopify
```

**Comment by marcowenk** [comment]
Hi Radyslav, 
Thanks again for following up! ShopApp_Shopify wasn’t imported correctly, but now I got it to work. Thanks

**Comment by marcowenk** [comment]
How would I start best when adding PayPal support?

**Comment by radyslavkrechet** [comment]
Our app doesn't support PayPal. There are two ways for a customer to pay by order: by credit card or by Apple Pay. For more details, you can look up the Shopify documentation with instruction of setup these features on the Shopify admin panel.

If you would like to add PayPal, you could fork "ShopApp Shopify" repo and implement an additional method by yourself. In the future, we may add this functionality. Right now we only have minimal features for work of marketplace in real life.
