### ISSUE TITLE
Cannot build after adding ShopApp_Shopify pod

### ISSUE THREAD

**Issue by ghassett** [rubygarage/shopapp-ios#194]
Hello, I can clone the ShopApp repo, do a `pod install`, and then successfully build the code in XCode 10.2.1.  However, once I add the ShopApp_Shopify pod to the `Podfile`, and install it via `pod install`, I get the following build error:

```
error: Multiple commands produce '/Users/ghassett/Library/Developer/Xcode/DerivedData/ShopApp-gbpikwhrdwpjhoherevxqxtsanho/Build/Products/Debug-iphonesimulator/ShopApp.app/Frameworks/ShopApp_Gateway.framework':
1) Target 'ShopApp' has copy command from '/Users/ghassett/Library/Developer/Xcode/DerivedData/ShopApp-gbpikwhrdwpjhoherevxqxtsanho/Build/Products/Debug-iphonesimulator/ShopApp_Gateway.framework' to '/Users/ghassett/Library/Developer/Xcode/DerivedData/ShopApp-gbpikwhrdwpjhoherevxqxtsanho/Build/Products/Debug-iphonesimulator/ShopApp.app/Frameworks/ShopApp_Gateway.framework'
2) That command depends on command in Target 'ShopApp': script phase “[CP] Embed Pods Frameworks”
```

Is there some other step that I need to make?  Apologies if I am missing something obvious.

Thanks -- looking forward to seeing it in action!

**Comment by marcowenk** [comment]
Hi,
I think you need to change both of your build system settings under file > project settings to legacy.

**Comment by radyslavkrechet** [comment]
@marcowenk, exactly!

**Comment by ghassett** [comment]
That did it - thanks for the speedy response!
