### ISSUE TITLE
Something Happening during Checkout

### ISSUE THREAD

**Issue by urbanintell** [rubygarage/shopapp-ios#197]
Hey guys I love this project thanks for making this open source.  

I almost got things up and running however, anytime I try to place order I get the "Something Happened" view controller but I am unsure what I need to do to debug this. I am also not sure if there is something for me to change on the Shopify end or on my end. Could I get some guidance on how to get a more descriptive error message from this screen?

**Comment by radyslavkrechet** [comment]
Hello, @urbanintell !

Look at the `paymentCallback` private function in the `CheckoutViewModel` and check `errorMessage` value of the `error` object. Also, you can look deeper and check `public func pay(with card: CreditCard, checkout: Checkout, billingAddress: Address, customerEmail: String, callback: @escaping RepoCallback<Order>)` in the `ShopifyAPI` to explore payment process step by step and find the reason of your problem.
